name: Discord tests

on: [push]

jobs:
  tests:
    name: Run tests
    runs-on: ubuntu-latest
    env:
      TEST_TOKEN: ${{ secrets.TEST_TOKEN }}
      TEST_GUILD: ${{ secrets.TEST_GUILD }}
      TEST_CHANNEL: ${{ secrets.TEST_CHANNEL }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup V
        uses: nocturlab/setup-vlang-action@v1
        with:
          id: v
          v-version: master

      - name: Test HTTP
        run: v test src/http_test.v